# ===========================
# Server Configuration
# ===========================
server.port=8080

# ===========================
# Thymeleaf Configuration
# ===========================
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

# ===========================
# PostgreSQL / Database Configuration
# ===========================
# Using environment variables for security

spring.datasource.url=jdbc:postgresql://dpg-d50omkemcj7s73erdgp0-a.oregon-postgres.render.com:5432/portfolio_backend_database_001
spring.datasource.username=portfolio_backend_database_001_user
spring.datasource.password=puXMAeLpSpIR4z2tl1va5fTeFEdW6hWI
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================
# Hibernate / JPA Configuration
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



openrouter.api.key=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
