@@ -15,10 +15,9 @@ spring.thymeleaf.mode=HTML
# PostgreSQL / Database Configuration
# ===========================
# Using environment variables for security

spring.datasource.url=jdbc:postgresql://dpg-d50omkemcj7s73erdgp0-a.oregon-postgres.render.com:5432/portfolio_backend_database_001
spring.datasource.username=portfolio_backend_database_001_user
spring.datasource.password=puXMAeLpSpIR4z2tl1va5fTeFEdW6hWI
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================
@@ -29,5 +28,4 @@ spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



openrouter.api.key=${AI_API_KEY}